[project]
name = 'Blockchain-Based-Land-Registry-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lien-recording]
path = 'contracts/lien-recording.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-registration]
path = 'contracts/property-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.title-transfer]
path = 'contracts/title-transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.zoning-compliance]
path = 'contracts/zoning-compliance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
